### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by dicook** [onnokleen/alfred#3]
Onno, Do you really mean to allow anyone to see and use  your API key when they download the data? I notice on the  web site it suggests each researcher should get their own. Yours is embedded into your get_alfred_series() function, which  means all users of the package are using your API key.

**Comment by onnokleen** [comment]
Thanks for asking but it is actually meant to be that way: I asked the FRED team back in 2017 whether including my API key as part of the R package is fine for them so more people can make use of their API. Their response was positive.
