### ISSUE TITLE
Need Dependency CURL on Mac

### ISSUE THREAD

**Issue by dbarclaylewis** [onnokleen/alfred#6]
Had an issue where mac users needed to install curl, or else they got the error "Download of specified time-series failed - did you misspell the identifier?"

**Comment by onnokleen** [comment]
Hi, could you please be more specific? What does install curl mean - the command line tool or an additional R package? Which versions of macOS?

**Comment by dbarclaylewis** [comment]
Sorry I don't know the version of macOS as it wasn't me that had the issue with it. it seems more like an issue with jsonlite depending on curl
https://cran.r-project.org/web/packages/curl/
The try statement hides the fact that jsonlite was missing the dependency.
if you remove the silent=True from line 160 you get an error: 
<simpleError: Required package curl not found. Please run: install.packages('curl')>

**Comment by onnokleen** [comment]
Ah, curl seems only to be a suggests and not a strict dependency. I will add curl to my dependency list with the next update.

**Comment by dbarclaylewis** [comment]
Thanks!

**Comment by onnokleen** [comment]
Should be ok in new release
