### ISSUE TITLE
Date when information is publicly available

### ISSUE THREAD

**Issue by MislavSag** [onnokleen/alfred#8]
It's the first time I am using ALFRED database.

Is it possible to get all history data with column that shows the date when the observation was first available to the public?

This is very important in forecasting. We should use the date when information was known. not the date which shows the period of observation. There is real time date but this date is the same for all observations.

**Comment by onnokleen** [comment]
Please look at the data. the real time date column should not be the same for all observations. If you think it's the case, please make a minimal reproducible example.

[https://stackoverflow.com/help/minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)
